# Generated by Django 5.2 on 2025-05-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
