# Generated by Django 5.2 on 2025-06-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_category_alter_ad_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
            ],
            options={
                'unique_together': {('ad', 'ip_address')},
            },
        ),
    ]
