# Generated by Django 5.2 on 2025-06-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ad_views_adview'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
