# Generated by Django 5.2 on 2025-07-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
