# Generated by Django 5.2.2 on 2025-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment_text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
