# Generated by Django 5.2.2 on 2025-08-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
