# Generated by Django 5.2.2 on 2025-09-07 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_ad_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('bool', 'Boolean'), ('choice', 'Choice')], default='text', max_length=12)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ads.category')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ads.attribute')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='AdAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('value_number', models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=14, null=True)),
                ('value_bool', models.BooleanField(blank=True, db_index=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ads.ad')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.attribute')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_values', to='ads.attributeoption')),
            ],
            options={
                'indexes': [models.Index(fields=['attribute', 'value_text'], name='ads_adattri_attribu_5bf1f6_idx'), models.Index(fields=['attribute', 'value_number'], name='ads_adattri_attribu_d12fe5_idx'), models.Index(fields=['attribute', 'value_bool'], name='ads_adattri_attribu_69179f_idx'), models.Index(fields=['attribute', 'option'], name='ads_adattri_attribu_80d7c7_idx')],
                'unique_together': {('ad', 'attribute')},
            },
        ),
    ]
