# Generated by Django 5.2.2 on 2025-10-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_attribute_attributeoption_adattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='ads.subcategory', verbose_name='Subcategory'),
        ),
    ]
