# Generated by Django 5.2 on 2025-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_location_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Покупець'), ('seller', 'Продавесь'), ('moderator', 'Модератор'), ('admin', 'Адмін')], default='buyer', max_length=20),
        ),
    ]
