# Generated by Django 5.2 on 2025-05-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_photo',
            field=models.JSONField(default=str),
        ),
    ]
