# Generated by Django 5.2 on 2025-05-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
