# Generated by Django 5.2 on 2025-05-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_phone',
            field=models.BooleanField(default=False),
        ),
    ]
